"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os, json
from importlib import import_module
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

if os.environ.get('MOD_WSGI') != 'true':
     load_dotenv('/etc/django/broodenbanket.env')
 
# --------------------
# Basis instellingen
#---------------------
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
 
DEBUG = os.getenv('DEBUG', 'FALSE') == 'True'
DJANGO_ENV = os.getenv('DJANGO_ENV','dev')
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')
LOGGING_MODULE = os.getenv('LOGGING_MODULE', 'config.logging_dev')
SITE_DOMAIN= os.getenv('SITE_DOMAIN')
 
# ------------------
# login/logout redirects
# ------------------
LOGIN_URL = "users:login"
LOGIN_REDIRECT_URL = "welkom"
LOGOUT_REDIRECT_URL = "welkom"
 
# ------------------
# Versioning
# -------------------
try:
    with open(BASE_DIR / "VERSION") as f:
        VERSION = f.read().strip()
except FileNotFoundError:
    VERSION = "unknown"
 
# -------------------
# Email settings
# -------------------
SERVER_EMAIL = os.getenv("SERVER_EMAIL", "receptenapps@kpnmail.nl")
 
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
 
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_USER_PASSWORD')
 
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
 
EMAIL_FAIL_SILENTLY = False
 
ADMINS = json.loads(os.getenv("ADMINS_JSON", "[]"))
if DJANGO_ENV == "prod":
    MANAGERS = ADMINS
 

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://odroid:8000",
    "http://192.168.178.116", 
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.recepten.apps.ReceptenConfig',
    'apps.users.apps.UsersConfig',
    'django_extensions',
    'easy_thumbnails',
    'crispy_forms',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
     'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST", "localhost"),
        'PORT': os.getenv("DB_PORT", "3306"),
    }
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
}
 

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (voor uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

print("BASE_DIR =", BASE_DIR)
print("Templates dir =", BASE_DIR / "templates")

# -------------------
# Logging inlezen
# -------------------
try:
    LOGGING = import_module(LOGGING_MODULE).LOGGING
except Exception as e:
    raise importError(f"Kon logginconfiguration niet importeren: {LOGGING_MODULE} ({e})")

